/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewRouteImport } from './routes/new'
import { Route as OldRouteImport } from './routes/old'
import { Route as NewIndexRouteImport } from './routes/new.index'
import { Route as NewCropTagRouteImport } from './routes/new.crop-tag'
import { Route as NewCsvExportRouteImport } from './routes/new.csv-export'
import { Route as NewImageCsvRouteImport } from './routes/new.image-csv'
import { Route as NewImagesToCsvRouteImport } from './routes/new.images-to-csv'
import { Route as NewPdfToImagesRouteImport } from './routes/new.pdf-to-images'
import { Route as NewReportRouteImport } from './routes/new.report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OldRoute = OldRouteImport.update({
  id: '/old',
  path: '/old',
  getParentRoute: () => rootRouteImport,
} as any)
const NewIndexRoute = NewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewRoute,
} as any)
const NewCropTagRoute = NewCropTagRouteImport.update({
  id: '/crop-tag',
  path: '/crop-tag',
  getParentRoute: () => NewRoute,
} as any)
const NewCsvExportRoute = NewCsvExportRouteImport.update({
  id: '/csv-export',
  path: '/csv-export',
  getParentRoute: () => NewRoute,
} as any)
const NewImageCsvRoute = NewImageCsvRouteImport.update({
  id: '/image-csv',
  path: '/image-csv',
  getParentRoute: () => NewRoute,
} as any)
const NewImagesToCsvRoute = NewImagesToCsvRouteImport.update({
  id: '/images-to-csv',
  path: '/images-to-csv',
  getParentRoute: () => NewRoute,
} as any)
const NewPdfToImagesRoute = NewPdfToImagesRouteImport.update({
  id: '/pdf-to-images',
  path: '/pdf-to-images',
  getParentRoute: () => NewRoute,
} as any)
const NewReportRoute = NewReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => NewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRouteWithChildren
  '/old': typeof OldRoute
  '/new/crop-tag': typeof NewCropTagRoute
  '/new/csv-export': typeof NewCsvExportRoute
  '/new/image-csv': typeof NewImageCsvRoute
  '/new/images-to-csv': typeof NewImagesToCsvRoute
  '/new/pdf-to-images': typeof NewPdfToImagesRoute
  '/new/report': typeof NewReportRoute
  '/new/': typeof NewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/old': typeof OldRoute
  '/new/crop-tag': typeof NewCropTagRoute
  '/new/csv-export': typeof NewCsvExportRoute
  '/new/image-csv': typeof NewImageCsvRoute
  '/new/images-to-csv': typeof NewImagesToCsvRoute
  '/new/pdf-to-images': typeof NewPdfToImagesRoute
  '/new/report': typeof NewReportRoute
  '/new': typeof NewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRouteWithChildren
  '/old': typeof OldRoute
  '/new/crop-tag': typeof NewCropTagRoute
  '/new/csv-export': typeof NewCsvExportRoute
  '/new/image-csv': typeof NewImageCsvRoute
  '/new/images-to-csv': typeof NewImagesToCsvRoute
  '/new/pdf-to-images': typeof NewPdfToImagesRoute
  '/new/report': typeof NewReportRoute
  '/new/': typeof NewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/old'
    | '/new/crop-tag'
    | '/new/csv-export'
    | '/new/image-csv'
    | '/new/images-to-csv'
    | '/new/pdf-to-images'
    | '/new/report'
    | '/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/old'
    | '/new/crop-tag'
    | '/new/csv-export'
    | '/new/image-csv'
    | '/new/images-to-csv'
    | '/new/pdf-to-images'
    | '/new/report'
    | '/new'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/old'
    | '/new/crop-tag'
    | '/new/csv-export'
    | '/new/image-csv'
    | '/new/images-to-csv'
    | '/new/pdf-to-images'
    | '/new/report'
    | '/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRouteWithChildren
  OldRoute: typeof OldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old': {
      id: '/old'
      path: '/old'
      fullPath: '/old'
      preLoaderRoute: typeof OldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/': {
      id: '/new/'
      path: '/'
      fullPath: '/new/'
      preLoaderRoute: typeof NewIndexRouteImport
      parentRoute: typeof NewRoute
    }
    '/new/crop-tag': {
      id: '/new/crop-tag'
      path: '/crop-tag'
      fullPath: '/new/crop-tag'
      preLoaderRoute: typeof NewCropTagRouteImport
      parentRoute: typeof NewRoute
    }
    '/new/csv-export': {
      id: '/new/csv-export'
      path: '/csv-export'
      fullPath: '/new/csv-export'
      preLoaderRoute: typeof NewCsvExportRouteImport
      parentRoute: typeof NewRoute
    }
    '/new/image-csv': {
      id: '/new/image-csv'
      path: '/image-csv'
      fullPath: '/new/image-csv'
      preLoaderRoute: typeof NewImageCsvRouteImport
      parentRoute: typeof NewRoute
    }
    '/new/images-to-csv': {
      id: '/new/images-to-csv'
      path: '/images-to-csv'
      fullPath: '/new/images-to-csv'
      preLoaderRoute: typeof NewImagesToCsvRouteImport
      parentRoute: typeof NewRoute
    }
    '/new/pdf-to-images': {
      id: '/new/pdf-to-images'
      path: '/pdf-to-images'
      fullPath: '/new/pdf-to-images'
      preLoaderRoute: typeof NewPdfToImagesRouteImport
      parentRoute: typeof NewRoute
    }
    '/new/report': {
      id: '/new/report'
      path: '/report'
      fullPath: '/new/report'
      preLoaderRoute: typeof NewReportRouteImport
      parentRoute: typeof NewRoute
    }
  }
}

interface NewRouteChildren {
  NewCropTagRoute: typeof NewCropTagRoute
  NewCsvExportRoute: typeof NewCsvExportRoute
  NewImageCsvRoute: typeof NewImageCsvRoute
  NewImagesToCsvRoute: typeof NewImagesToCsvRoute
  NewPdfToImagesRoute: typeof NewPdfToImagesRoute
  NewReportRoute: typeof NewReportRoute
  NewIndexRoute: typeof NewIndexRoute
}

const NewRouteChildren: NewRouteChildren = {
  NewCropTagRoute: NewCropTagRoute,
  NewCsvExportRoute: NewCsvExportRoute,
  NewImageCsvRoute: NewImageCsvRoute,
  NewImagesToCsvRoute: NewImagesToCsvRoute,
  NewPdfToImagesRoute: NewPdfToImagesRoute,
  NewReportRoute: NewReportRoute,
  NewIndexRoute: NewIndexRoute,
}

const NewRouteWithChildren = NewRoute._addFileChildren(NewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRouteWithChildren,
  OldRoute: OldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
