/**
 * ReportFlow — /new/report tab.
 *
 * Displays the report generated by CsvImportFlow's "Generate report" button.
 * • First column: CSV filename (read-only)
 * • Middle columns: data columns (read-only)
 * • Last column: user notes (editable)
 * • Context rows (exposed around matches) are dimmed.
 * • "Export CSV" downloads the full table.
 * • "Clear report" resets the store and navigates back to /new/csv-export.
 */
import { useCallback } from "react";
import { useNavigate } from "@tanstack/react-router";
import { toast } from "sonner";
import { Download, Trash2, ArrowLeft, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useAppStore } from "@/contexts/AppStore";
import { toCsv } from "@/lib/new-flow/csv-extract";
import { timestamp } from "@/lib/receipt-utils";

export function ReportFlow() {
  const { reportRows, setReportRows, reportColumns, setReportColumns } = useAppStore();
  const navigate = useNavigate();

  const matchCount   = reportRows.filter((r) => !r.isContext).length;
  const ctxCount     = reportRows.filter((r) => r.isContext).length;
  const fileCount    = new Set(reportRows.map((r) => r.filename)).size;

  const updateNote = (id: string, notes: string) =>
    setReportRows((prev) => prev.map((r) => r.id === id ? { ...r, notes } : r));

  const updateCell = (id: string, cellIdx: number, value: string) =>
    setReportRows((prev) =>
      prev.map((r) => {
        if (r.id !== id) return r;
        const cells = [...r.cells];
        cells[cellIdx] = value;
        return { ...r, cells };
      }),
    );

  const downloadReport = useCallback(() => {
    if (!reportRows.length) return;
    const cols = ["filename", ...reportColumns, "notes"];
    const rows = reportRows.map((r) => [r.filename, ...r.cells, r.notes]);
    const csv  = toCsv(cols, rows);
    const a    = document.createElement("a");
    a.href     = URL.createObjectURL(new Blob([csv], { type: "text/csv" }));
    a.download = `report.${timestamp()}.csv`;
    a.click();
    setTimeout(() => URL.revokeObjectURL(a.href), 15_000);
    toast.success("Report exported.");
  }, [reportRows, reportColumns]);

  const clearReport = () => {
    setReportRows([]);
    setReportColumns([]);
    navigate({ to: "/new/csv-export" });
  };

  // ── empty state ───────────────────────────────────────────────────────────

  if (!reportRows.length) {
    return (
      <div className="flex flex-1 flex-col items-center justify-center gap-4 p-12 text-center">
        <FileText className="h-12 w-12 text-muted-foreground/40" />
        <div>
          <p className="text-sm font-medium text-muted-foreground">No report yet</p>
          <p className="mt-1 text-xs text-muted-foreground">
            Go to <strong>CSV Import/Export</strong>, load files, set a filter, and click{" "}
            <strong>Generate report</strong>.
          </p>
        </div>
        <Button size="sm" variant="outline" onClick={() => navigate({ to: "/new/csv-export" })}>
          <ArrowLeft className="mr-1.5 h-3.5 w-3.5" />Go to CSV Import/Export
        </Button>
      </div>
    );
  }

  // ── report table ──────────────────────────────────────────────────────────

  return (
    <div className="flex flex-1 flex-col">
      {/* Header bar */}
      <div className="flex flex-wrap items-center gap-2 border-b border-border px-4 py-2">
        <Button size="sm" variant="ghost" className="h-7 gap-1 text-xs text-muted-foreground"
          onClick={() => navigate({ to: "/new/csv-export" })}>
          <ArrowLeft className="h-3.5 w-3.5" />Back
        </Button>

        <span className="text-sm font-semibold">Report</span>
        <span className="text-xs text-muted-foreground">
          {matchCount} match{matchCount !== 1 ? "es" : ""}
          {ctxCount > 0 && ` + ${ctxCount} context`}
          {" · "}{fileCount} file{fileCount !== 1 ? "s" : ""}
          {" · "}{reportColumns.length} column{reportColumns.length !== 1 ? "s" : ""}
        </span>

        <div className="ml-auto flex items-center gap-2">
          <Button size="sm" variant="outline" className="h-7 gap-1 text-xs" onClick={downloadReport}>
            <Download className="h-3.5 w-3.5" />Export CSV
          </Button>
          <Button size="sm" variant="ghost" className="h-7 gap-1 text-xs text-destructive" onClick={clearReport}>
            <Trash2 className="h-3.5 w-3.5" />Clear
          </Button>
        </div>
      </div>

      {/* Table */}
      <div className="flex-1 overflow-auto">
        <table className="min-w-full text-xs">
          <thead className="sticky top-0 z-10 bg-muted shadow-sm">
            <tr>
              {/* filename */}
              <th className="whitespace-nowrap border-b border-r border-border px-3 py-2 text-left font-semibold text-muted-foreground">
                filename
              </th>
              {/* data columns */}
              {reportColumns.map((col, ci) => (
                <th key={ci} className="whitespace-nowrap border-b border-border px-3 py-2 text-left font-semibold">
                  {col}
                </th>
              ))}
              {/* notes */}
              <th className="whitespace-nowrap border-b border-l border-border px-3 py-2 text-left font-semibold text-primary">
                notes
              </th>
            </tr>
          </thead>
          <tbody>
            {reportRows.map((rr, ri) => (
              <tr key={rr.id}
                className={`border-b border-border ${
                  rr.isContext
                    ? "bg-muted/20 opacity-60"
                    : ri % 2 === 1 ? "bg-muted/10" : ""
                }`}>
                {/* filename — read-only */}
                <td className="whitespace-nowrap border-r border-border px-3 py-1 font-mono text-muted-foreground">
                  {rr.filename}
                </td>
                {/* data cells — editable */}
                {rr.cells.map((cell, ci) => (
                  <td key={ci} className="whitespace-nowrap px-1 py-0.5">
                    <input
                      className="w-full rounded bg-transparent px-1.5 py-0.5 focus:bg-background focus:outline-none focus:ring-1 focus:ring-primary"
                      value={cell}
                      onChange={(e) => updateCell(rr.id, ci, e.target.value)}
                    />
                  </td>
                ))}
                {/* notes — editable */}
                <td className="border-l border-border px-1 py-0.5">
                  <input
                    className="w-full min-w-32 rounded bg-transparent px-1.5 py-0.5 focus:bg-background focus:outline-none focus:ring-1 focus:ring-primary"
                    value={rr.notes}
                    placeholder="Add note…"
                    onChange={(e) => updateNote(rr.id, e.target.value)}
                  />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
